-- MetaGen PostgreSQL history. Review and commit this file.
return {
    bundle = "auth",
    contentHash = "b3b04c10ed7029809711fdd5d844ce3a16b11abeed5e068c216acde84d0a344b",
    id = "0001_baseline_current_schema",
    name = "Baseline current schema",
    operations = {
        [1] = {
            kind = "createSchema",
            persistentId = "public",
            sql = "CREATE SCHEMA IF NOT EXISTS \"public\";",
        },
        [2] = {
            kind = "createTable",
            persistentId = "postgres.accounts",
            sql = "CREATE TABLE \"public\".\"accounts\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"flags\" bigint DEFAULT 0 NOT NULL,\
    \"name\" text NOT NULL,\
    \"email\" text DEFAULT '' NOT NULL,\
    \"registration_timestamp\" bigint NOT NULL,\
    \"last_login_timestamp\" bigint DEFAULT 0 NOT NULL,\
    \"blob\" bytea NULL,\
    CONSTRAINT \"accounts_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"unique_name\" UNIQUE (\"name\")\
);",
        },
    },
    parentHash = "b614a3b960859fca9ad77b55994ce3b85591861632f0f58901c8be734860462e",
    sql = "BEGIN;\
CREATE SCHEMA IF NOT EXISTS \"public\";\
CREATE TABLE \"public\".\"accounts\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"flags\" bigint DEFAULT 0 NOT NULL,\
    \"name\" text NOT NULL,\
    \"email\" text DEFAULT '' NOT NULL,\
    \"registration_timestamp\" bigint NOT NULL,\
    \"last_login_timestamp\" bigint DEFAULT 0 NOT NULL,\
    \"blob\" bytea NULL,\
    CONSTRAINT \"accounts_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"unique_name\" UNIQUE (\"name\")\
);\
COMMIT;\
",
    targetHash = "0d9fe7fdd318ee4625ab9e4edaec2c1ecff1fa91f0db4f79c752b24996c583be",
    transactional = true,
}
