-- MetaGen PostgreSQL history. Review and commit this file.
return {
    bundle = "auth",
    contentHash = "68371a80a57cf1127a8b7b329eae08e7ad70ba960b4683c23482926439632a22",
    id = "0002_add_permission_model",
    name = "add_permission_model",
    operations = {
        [1] = {
            kind = "createTable",
            persistentId = "postgres.permission_groups",
            sql = "CREATE TABLE \"public\".\"permission_groups\"\
(\
    \"id\" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text NOT NULL,\
    CONSTRAINT \"permission_groups_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"permission_groups_unique_name\" UNIQUE (\"name\")\
);",
        },
        [2] = {
            kind = "createTable",
            persistentId = "postgres.account_permission_groups",
            sql = "CREATE TABLE \"public\".\"account_permission_groups\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"account_id\" bigint NOT NULL,\
    \"permission_group_id\" smallint NOT NULL,\
    CONSTRAINT \"account_permission_groups_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"account_permission_group_key\" UNIQUE (\"account_id\", \"permission_group_id\"),\
    CONSTRAINT \"account_permission_groups_account_fk\" FOREIGN KEY (\"account_id\") REFERENCES \"public\".\"accounts\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE,\
    CONSTRAINT \"account_permission_groups_group_fk\" FOREIGN KEY (\"permission_group_id\") REFERENCES \"public\".\"permission_groups\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);",
        },
        [3] = {
            kind = "createTable",
            persistentId = "postgres.permissions",
            sql = "CREATE TABLE \"public\".\"permissions\"\
(\
    \"id\" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text NOT NULL,\
    CONSTRAINT \"permissions_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"permissions_unique_name\" UNIQUE (\"name\")\
);",
        },
        [4] = {
            kind = "createTable",
            persistentId = "postgres.account_permissions",
            sql = "CREATE TABLE \"public\".\"account_permissions\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"account_id\" bigint NOT NULL,\
    \"permission_id\" smallint NOT NULL,\
    \"value\" bigint DEFAULT 1 NOT NULL,\
    CONSTRAINT \"account_permissions_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"account_permission_key\" UNIQUE (\"account_id\", \"permission_id\"),\
    CONSTRAINT \"account_permissions_account_fk\" FOREIGN KEY (\"account_id\") REFERENCES \"public\".\"accounts\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE,\
    CONSTRAINT \"account_permissions_permission_fk\" FOREIGN KEY (\"permission_id\") REFERENCES \"public\".\"permissions\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);",
        },
        [5] = {
            kind = "createTable",
            persistentId = "postgres.permission_group_data",
            sql = "CREATE TABLE \"public\".\"permission_group_data\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"group_id\" smallint NOT NULL,\
    \"permission_id\" smallint NOT NULL,\
    \"value\" bigint DEFAULT 1 NOT NULL,\
    CONSTRAINT \"permission_group_data_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"permission_group_data_key\" UNIQUE (\"group_id\", \"permission_id\"),\
    CONSTRAINT \"permission_group_data_group_fk\" FOREIGN KEY (\"group_id\") REFERENCES \"public\".\"permission_groups\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE,\
    CONSTRAINT \"permission_group_data_permission_fk\" FOREIGN KEY (\"permission_id\") REFERENCES \"public\".\"permissions\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);",
        },
    },
    parentHash = "0d9fe7fdd318ee4625ab9e4edaec2c1ecff1fa91f0db4f79c752b24996c583be",
    sql = "BEGIN;\
CREATE TABLE \"public\".\"permission_groups\"\
(\
    \"id\" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text NOT NULL,\
    CONSTRAINT \"permission_groups_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"permission_groups_unique_name\" UNIQUE (\"name\")\
);\
CREATE TABLE \"public\".\"account_permission_groups\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"account_id\" bigint NOT NULL,\
    \"permission_group_id\" smallint NOT NULL,\
    CONSTRAINT \"account_permission_groups_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"account_permission_group_key\" UNIQUE (\"account_id\", \"permission_group_id\"),\
    CONSTRAINT \"account_permission_groups_account_fk\" FOREIGN KEY (\"account_id\") REFERENCES \"public\".\"accounts\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE,\
    CONSTRAINT \"account_permission_groups_group_fk\" FOREIGN KEY (\"permission_group_id\") REFERENCES \"public\".\"permission_groups\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);\
CREATE TABLE \"public\".\"permissions\"\
(\
    \"id\" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text NOT NULL,\
    CONSTRAINT \"permissions_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"permissions_unique_name\" UNIQUE (\"name\")\
);\
CREATE TABLE \"public\".\"account_permissions\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"account_id\" bigint NOT NULL,\
    \"permission_id\" smallint NOT NULL,\
    \"value\" bigint DEFAULT 1 NOT NULL,\
    CONSTRAINT \"account_permissions_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"account_permission_key\" UNIQUE (\"account_id\", \"permission_id\"),\
    CONSTRAINT \"account_permissions_account_fk\" FOREIGN KEY (\"account_id\") REFERENCES \"public\".\"accounts\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE,\
    CONSTRAINT \"account_permissions_permission_fk\" FOREIGN KEY (\"permission_id\") REFERENCES \"public\".\"permissions\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);\
CREATE TABLE \"public\".\"permission_group_data\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"group_id\" smallint NOT NULL,\
    \"permission_id\" smallint NOT NULL,\
    \"value\" bigint DEFAULT 1 NOT NULL,\
    CONSTRAINT \"permission_group_data_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"permission_group_data_key\" UNIQUE (\"group_id\", \"permission_id\"),\
    CONSTRAINT \"permission_group_data_group_fk\" FOREIGN KEY (\"group_id\") REFERENCES \"public\".\"permission_groups\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE,\
    CONSTRAINT \"permission_group_data_permission_fk\" FOREIGN KEY (\"permission_id\") REFERENCES \"public\".\"permissions\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);\
COMMIT;\
",
    targetHash = "be37cd3f464296db566a27a0c02284ce6d7885d42d80c51b1d61188816c45f3d",
    transactional = true,
}
