-- MetaGen PostgreSQL history. Review and commit this file.
return {
    bundle = "character",
    contentHash = "4ae660feab50a5c0f61359046fcf09467805855ce0e6be8d597a4e53326c84ef",
    id = "0001_baseline_current_schema",
    name = "Baseline current schema",
    operations = {
        [1] = {
            kind = "createSchema",
            persistentId = "public",
            sql = "CREATE SCHEMA IF NOT EXISTS \"public\";",
        },
        [2] = {
            kind = "createTable",
            persistentId = "postgres.characters",
            sql = "CREATE TABLE \"public\".\"characters\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"account_id\" bigint DEFAULT 0 NOT NULL,\
    \"name\" varchar(12) NOT NULL,\
    \"total_time\" integer DEFAULT 0 NOT NULL,\
    \"level_time\" integer DEFAULT 0 NOT NULL,\
    \"logout_time\" bigint DEFAULT 0 NOT NULL,\
    \"flags\" integer DEFAULT 0 NOT NULL,\
    \"race_gender_class\" smallint NOT NULL,\
    \"level\" smallint DEFAULT 1 NOT NULL,\
    \"experience_points\" bigint DEFAULT 0 NOT NULL,\
    \"map_id\" integer DEFAULT 0 NOT NULL,\
    \"position_x\" real DEFAULT 0.0 NOT NULL,\
    \"position_y\" real DEFAULT 0.0 NOT NULL,\
    \"position_z\" real DEFAULT 0.0 NOT NULL,\
    \"position_o\" real DEFAULT 0.0 NOT NULL,\
    CONSTRAINT \"characters_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"characters_unique_name\" UNIQUE (\"name\"),\
    CONSTRAINT \"characters_name_length\" CHECK (char_length(name) >= 2)\
);",
        },
        [3] = {
            kind = "createTable",
            persistentId = "postgres.character_currency",
            sql = "CREATE TABLE \"public\".\"character_currency\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"character_id\" bigint NOT NULL,\
    \"currency_id\" smallint NOT NULL,\
    \"value\" bigint DEFAULT 0 NOT NULL,\
    CONSTRAINT \"character_currency_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"character_currency_key\" UNIQUE (\"character_id\", \"currency_id\"),\
    CONSTRAINT \"character_currency_character_fk\" FOREIGN KEY (\"character_id\") REFERENCES \"public\".\"characters\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);",
        },
        [4] = {
            kind = "createTable",
            persistentId = "postgres.item_instances",
            sql = "CREATE TABLE \"public\".\"item_instances\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"item_id\" integer NOT NULL,\
    \"owner_id\" bigint NOT NULL,\
    \"count\" smallint NOT NULL,\
    \"durability\" smallint NOT NULL,\
    CONSTRAINT \"item_instances_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"item_instances_owner_id_id_key\" UNIQUE (\"owner_id\", \"id\"),\
    CONSTRAINT \"item_instances_owner_fk\" FOREIGN KEY (\"owner_id\") REFERENCES \"public\".\"characters\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);",
        },
        [5] = {
            kind = "createTable",
            persistentId = "postgres.character_items",
            sql = "CREATE TABLE \"public\".\"character_items\"\
(\
    \"character_id\" bigint NOT NULL,\
    \"container\" bigint NOT NULL,\
    \"slot\" smallint NOT NULL,\
    \"item_instance_id\" bigint NOT NULL,\
    CONSTRAINT \"unique_item_instance_id\" UNIQUE (\"item_instance_id\"),\
    CONSTRAINT \"character_items_character_container_slot_key\" UNIQUE (\"character_id\", \"container\", \"slot\"),\
    CONSTRAINT \"character_items_character_fk\" FOREIGN KEY (\"character_id\") REFERENCES \"public\".\"characters\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE,\
    CONSTRAINT \"character_items_owner_item_fk\" FOREIGN KEY (\"character_id\", \"item_instance_id\") REFERENCES \"public\".\"item_instances\" (\"owner_id\", \"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);",
        },
        [6] = {
            kind = "createTable",
            persistentId = "postgres.character_permission_groups",
            sql = "CREATE TABLE \"public\".\"character_permission_groups\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"character_id\" bigint NOT NULL,\
    \"permission_group_id\" smallint NOT NULL,\
    CONSTRAINT \"character_permission_groups_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"character_permission_group_key\" UNIQUE (\"character_id\", \"permission_group_id\"),\
    CONSTRAINT \"character_permission_groups_character_fk\" FOREIGN KEY (\"character_id\") REFERENCES \"public\".\"characters\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);",
        },
        [7] = {
            kind = "createTable",
            persistentId = "postgres.character_permissions",
            sql = "CREATE TABLE \"public\".\"character_permissions\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"character_id\" bigint NOT NULL,\
    \"permission_id\" smallint NOT NULL,\
    CONSTRAINT \"character_permissions_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"character_permission_key\" UNIQUE (\"character_id\", \"permission_id\"),\
    CONSTRAINT \"character_permissions_character_fk\" FOREIGN KEY (\"character_id\") REFERENCES \"public\".\"characters\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);",
        },
        [8] = {
            kind = "addIndex",
            persistentId = "postgres.characters.account_id_id_idx",
            sql = "CREATE INDEX \"characters_account_id_id_idx\" ON \"public\".\"characters\" (\"account_id\" ASC, \"id\" ASC);",
        },
        [9] = {
            kind = "addIndex",
            persistentId = "postgres.item_instances.owner_id_id_idx",
            sql = "CREATE INDEX \"item_instances_owner_id_id_idx\" ON \"public\".\"item_instances\" (\"owner_id\" ASC, \"id\" ASC);",
        },
    },
    parentHash = "7eba43c751f1cbe5093ee5a85dccfdc6bdab2d17479b8eb93863ea7e3312f82b",
    sql = "BEGIN;\
CREATE SCHEMA IF NOT EXISTS \"public\";\
CREATE TABLE \"public\".\"characters\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"account_id\" bigint DEFAULT 0 NOT NULL,\
    \"name\" varchar(12) NOT NULL,\
    \"total_time\" integer DEFAULT 0 NOT NULL,\
    \"level_time\" integer DEFAULT 0 NOT NULL,\
    \"logout_time\" bigint DEFAULT 0 NOT NULL,\
    \"flags\" integer DEFAULT 0 NOT NULL,\
    \"race_gender_class\" smallint NOT NULL,\
    \"level\" smallint DEFAULT 1 NOT NULL,\
    \"experience_points\" bigint DEFAULT 0 NOT NULL,\
    \"map_id\" integer DEFAULT 0 NOT NULL,\
    \"position_x\" real DEFAULT 0.0 NOT NULL,\
    \"position_y\" real DEFAULT 0.0 NOT NULL,\
    \"position_z\" real DEFAULT 0.0 NOT NULL,\
    \"position_o\" real DEFAULT 0.0 NOT NULL,\
    CONSTRAINT \"characters_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"characters_unique_name\" UNIQUE (\"name\"),\
    CONSTRAINT \"characters_name_length\" CHECK (char_length(name) >= 2)\
);\
CREATE TABLE \"public\".\"character_currency\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"character_id\" bigint NOT NULL,\
    \"currency_id\" smallint NOT NULL,\
    \"value\" bigint DEFAULT 0 NOT NULL,\
    CONSTRAINT \"character_currency_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"character_currency_key\" UNIQUE (\"character_id\", \"currency_id\"),\
    CONSTRAINT \"character_currency_character_fk\" FOREIGN KEY (\"character_id\") REFERENCES \"public\".\"characters\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);\
CREATE TABLE \"public\".\"item_instances\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"item_id\" integer NOT NULL,\
    \"owner_id\" bigint NOT NULL,\
    \"count\" smallint NOT NULL,\
    \"durability\" smallint NOT NULL,\
    CONSTRAINT \"item_instances_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"item_instances_owner_id_id_key\" UNIQUE (\"owner_id\", \"id\"),\
    CONSTRAINT \"item_instances_owner_fk\" FOREIGN KEY (\"owner_id\") REFERENCES \"public\".\"characters\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);\
CREATE TABLE \"public\".\"character_items\"\
(\
    \"character_id\" bigint NOT NULL,\
    \"container\" bigint NOT NULL,\
    \"slot\" smallint NOT NULL,\
    \"item_instance_id\" bigint NOT NULL,\
    CONSTRAINT \"unique_item_instance_id\" UNIQUE (\"item_instance_id\"),\
    CONSTRAINT \"character_items_character_container_slot_key\" UNIQUE (\"character_id\", \"container\", \"slot\"),\
    CONSTRAINT \"character_items_character_fk\" FOREIGN KEY (\"character_id\") REFERENCES \"public\".\"characters\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE,\
    CONSTRAINT \"character_items_owner_item_fk\" FOREIGN KEY (\"character_id\", \"item_instance_id\") REFERENCES \"public\".\"item_instances\" (\"owner_id\", \"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);\
CREATE TABLE \"public\".\"character_permission_groups\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"character_id\" bigint NOT NULL,\
    \"permission_group_id\" smallint NOT NULL,\
    CONSTRAINT \"character_permission_groups_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"character_permission_group_key\" UNIQUE (\"character_id\", \"permission_group_id\"),\
    CONSTRAINT \"character_permission_groups_character_fk\" FOREIGN KEY (\"character_id\") REFERENCES \"public\".\"characters\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);\
CREATE TABLE \"public\".\"character_permissions\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"character_id\" bigint NOT NULL,\
    \"permission_id\" smallint NOT NULL,\
    CONSTRAINT \"character_permissions_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"character_permission_key\" UNIQUE (\"character_id\", \"permission_id\"),\
    CONSTRAINT \"character_permissions_character_fk\" FOREIGN KEY (\"character_id\") REFERENCES \"public\".\"characters\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);\
CREATE INDEX \"characters_account_id_id_idx\" ON \"public\".\"characters\" (\"account_id\" ASC, \"id\" ASC);\
CREATE INDEX \"item_instances_owner_id_id_idx\" ON \"public\".\"item_instances\" (\"owner_id\" ASC, \"id\" ASC);\
COMMIT;\
",
    targetHash = "7906646833f1a5815ae1ee1f03ae61c117723fb7125d37a30c92d627885bc25f",
    transactional = true,
}
