-- MetaGen PostgreSQL history. Review and commit this file.
return {
    bundle = "character",
    contentHash = "04207fc71781062db2ef693838f582f251274701346de7b492e544ec58c8a1cb",
    id = "0004_add_faction_system",
    name = "add_faction_system",
    operations = {
        [1] = {
            kind = "createTable",
            persistentId = "postgres.character_reputations",
            sql = "CREATE TABLE \"public\".\"character_reputations\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"character_id\" bigint NOT NULL,\
    \"faction_id\" smallint NOT NULL,\
    \"value\" integer DEFAULT 0 NOT NULL,\
    \"flags\" smallint DEFAULT 0 NOT NULL,\
    CONSTRAINT \"character_reputations_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"character_reputations_character_faction_key\" UNIQUE (\"character_id\", \"faction_id\"),\
    CONSTRAINT \"character_reputations_character_fk\" FOREIGN KEY (\"character_id\") REFERENCES \"public\".\"characters\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);",
        },
        [2] = {
            kind = "addColumn",
            persistentId = "postgres.characters.faction_id",
            sql = "ALTER TABLE \"public\".\"characters\" ADD COLUMN \"faction_id\" smallint DEFAULT 0 NOT NULL;",
        },
    },
    parentHash = "f590c458be6688f0a1ae5d90eacf1230ba69d13f08118f30becc163a679cffd4",
    sql = "BEGIN;\
CREATE TABLE \"public\".\"character_reputations\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"character_id\" bigint NOT NULL,\
    \"faction_id\" smallint NOT NULL,\
    \"value\" integer DEFAULT 0 NOT NULL,\
    \"flags\" smallint DEFAULT 0 NOT NULL,\
    CONSTRAINT \"character_reputations_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"character_reputations_character_faction_key\" UNIQUE (\"character_id\", \"faction_id\"),\
    CONSTRAINT \"character_reputations_character_fk\" FOREIGN KEY (\"character_id\") REFERENCES \"public\".\"characters\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);\
ALTER TABLE \"public\".\"characters\" ADD COLUMN \"faction_id\" smallint DEFAULT 0 NOT NULL;\
COMMIT;\
",
    targetHash = "c1d0742226192cd3a2b86be7096c7b533b9b6bbaee964e05c9be09ce07299018",
    transactional = true,
}
