-- MetaGen PostgreSQL history. Review and commit this file.
return {
    bundle = "world",
    contentHash = "ad7908e251357e716031c0f22a67a1e593074b40cb044a4654bbabb9309eaca1",
    id = "0001_baseline_current_schema",
    name = "Baseline current schema",
    operations = {
        [1] = {
            kind = "createSchema",
            persistentId = "public",
            sql = "CREATE SCHEMA IF NOT EXISTS \"public\";",
        },
        [2] = {
            kind = "createTable",
            persistentId = "postgres.creature_templates",
            sql = "CREATE TABLE \"public\".\"creature_templates\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"flags\" integer DEFAULT 0 NOT NULL,\
    \"name\" text DEFAULT 'Unknown' NOT NULL,\
    \"subname\" text DEFAULT '' NOT NULL,\
    \"display_id\" integer DEFAULT 0 NOT NULL,\
    \"scale\" real DEFAULT 1.0 NOT NULL,\
    \"min_level\" smallint DEFAULT 1 NOT NULL,\
    \"max_level\" smallint DEFAULT 1 NOT NULL,\
    \"armor_mod\" real DEFAULT 1.0 NOT NULL,\
    \"health_mod\" real DEFAULT 1.0 NOT NULL,\
    \"resource_mod\" real DEFAULT 1.0 NOT NULL,\
    \"damage_mod\" real DEFAULT 1.0 NOT NULL,\
    \"script_name\" text DEFAULT '' NOT NULL,\
    CONSTRAINT \"creature_templates_pkey\" PRIMARY KEY (\"id\")\
);",
        },
        [3] = {
            kind = "createTable",
            persistentId = "postgres.creatures",
            sql = "CREATE TABLE \"public\".\"creatures\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"template_id\" integer NOT NULL,\
    \"display_id\" integer NOT NULL,\
    \"map_id\" integer NOT NULL,\
    \"position_x\" real NOT NULL,\
    \"position_y\" real NOT NULL,\
    \"position_z\" real NOT NULL,\
    \"position_o\" real NOT NULL,\
    \"script_name\" text DEFAULT '' NOT NULL,\
    CONSTRAINT \"creatures_pkey\" PRIMARY KEY (\"id\")\
);",
        },
        [4] = {
            kind = "createTable",
            persistentId = "postgres.currency",
            sql = "CREATE TABLE \"public\".\"currency\"\
(\
    \"id\" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text NOT NULL,\
    CONSTRAINT \"currency_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"currency_unique_name\" UNIQUE (\"name\")\
);",
        },
        [5] = {
            kind = "createTable",
            persistentId = "postgres.item_armor_templates",
            sql = "CREATE TABLE \"public\".\"item_armor_templates\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"equip_type\" smallint DEFAULT 0 NOT NULL,\
    \"bonus_armor\" integer DEFAULT 0 NOT NULL,\
    CONSTRAINT \"item_armor_templates_pkey\" PRIMARY KEY (\"id\")\
);",
        },
        [6] = {
            kind = "createTable",
            persistentId = "postgres.item_shield_templates",
            sql = "CREATE TABLE \"public\".\"item_shield_templates\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"bonus_armor\" integer DEFAULT 0 NOT NULL,\
    \"block\" integer DEFAULT 0 NOT NULL,\
    CONSTRAINT \"item_shield_templates_pkey\" PRIMARY KEY (\"id\")\
);",
        },
        [7] = {
            kind = "createTable",
            persistentId = "postgres.item_stat_templates",
            sql = "CREATE TABLE \"public\".\"item_stat_templates\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"stat_type_1\" smallint DEFAULT 0 NOT NULL,\
    \"stat_type_2\" smallint DEFAULT 0 NOT NULL,\
    \"stat_type_3\" smallint DEFAULT 0 NOT NULL,\
    \"stat_type_4\" smallint DEFAULT 0 NOT NULL,\
    \"stat_type_5\" smallint DEFAULT 0 NOT NULL,\
    \"stat_type_6\" smallint DEFAULT 0 NOT NULL,\
    \"stat_type_7\" smallint DEFAULT 0 NOT NULL,\
    \"stat_type_8\" smallint DEFAULT 0 NOT NULL,\
    \"stat_value_1\" integer DEFAULT 0 NOT NULL,\
    \"stat_value_2\" integer DEFAULT 0 NOT NULL,\
    \"stat_value_3\" integer DEFAULT 0 NOT NULL,\
    \"stat_value_4\" integer DEFAULT 0 NOT NULL,\
    \"stat_value_5\" integer DEFAULT 0 NOT NULL,\
    \"stat_value_6\" integer DEFAULT 0 NOT NULL,\
    \"stat_value_7\" integer DEFAULT 0 NOT NULL,\
    \"stat_value_8\" integer DEFAULT 0 NOT NULL,\
    CONSTRAINT \"item_stat_templates_pkey\" PRIMARY KEY (\"id\")\
);",
        },
        [8] = {
            kind = "createTable",
            persistentId = "postgres.item_templates",
            sql = "CREATE TABLE \"public\".\"item_templates\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"display_id\" integer DEFAULT 0 NOT NULL,\
    \"bind\" smallint DEFAULT 0 NOT NULL,\
    \"rarity\" smallint DEFAULT 0 NOT NULL,\
    \"category\" smallint DEFAULT 1 NOT NULL,\
    \"type\" smallint DEFAULT 1 NOT NULL,\
    \"virtual_level\" smallint DEFAULT 0 NOT NULL,\
    \"required_level\" smallint DEFAULT 0 NOT NULL,\
    \"durability\" integer DEFAULT 0 NOT NULL,\
    \"icon_id\" integer DEFAULT 0 NOT NULL,\
    \"name\" text NOT NULL,\
    \"description\" text DEFAULT '' NOT NULL,\
    \"armor\" integer DEFAULT 0 NOT NULL,\
    \"stat_template_id\" integer DEFAULT 0 NOT NULL,\
    \"armor_template_id\" integer DEFAULT 0 NOT NULL,\
    \"weapon_template_id\" integer DEFAULT 0 NOT NULL,\
    \"shield_template_id\" integer DEFAULT 0 NOT NULL,\
    CONSTRAINT \"item_templates_pkey\" PRIMARY KEY (\"id\")\
);",
        },
        [9] = {
            kind = "createTable",
            persistentId = "postgres.item_weapon_templates",
            sql = "CREATE TABLE \"public\".\"item_weapon_templates\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"weapon_style\" smallint DEFAULT 0 NOT NULL,\
    \"min_damage\" integer DEFAULT 0 NOT NULL,\
    \"max_damage\" integer DEFAULT 0 NOT NULL,\
    \"speed\" real DEFAULT 1.0 NOT NULL,\
    CONSTRAINT \"item_weapon_templates_pkey\" PRIMARY KEY (\"id\")\
);",
        },
        [10] = {
            kind = "createTable",
            persistentId = "postgres.maps",
            sql = "CREATE TABLE \"public\".\"maps\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"flags\" integer DEFAULT 0 NOT NULL,\
    \"internal_name\" text DEFAULT '' NOT NULL,\
    \"name\" text DEFAULT '' NOT NULL,\
    \"type\" smallint DEFAULT 0 NOT NULL,\
    \"max_players\" smallint DEFAULT 0 NOT NULL,\
    CONSTRAINT \"maps_pkey\" PRIMARY KEY (\"id\")\
);",
        },
        [11] = {
            kind = "createTable",
            persistentId = "postgres.map_locations",
            sql = "CREATE TABLE \"public\".\"map_locations\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text DEFAULT '' NOT NULL,\
    \"map_id\" integer NOT NULL,\
    \"position_x\" real DEFAULT 0.0 NOT NULL,\
    \"position_y\" real DEFAULT 0.0 NOT NULL,\
    \"position_z\" real DEFAULT 0.0 NOT NULL,\
    \"position_o\" real DEFAULT 0.0 NOT NULL,\
    CONSTRAINT \"map_locations_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"map_locations_map_fk\" FOREIGN KEY (\"map_id\") REFERENCES \"public\".\"maps\" (\"id\") ON UPDATE NO ACTION ON DELETE NO ACTION\
);",
        },
        [12] = {
            kind = "createTable",
            persistentId = "postgres.permission_groups",
            sql = "CREATE TABLE \"public\".\"permission_groups\"\
(\
    \"id\" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text NOT NULL,\
    CONSTRAINT \"permission_groups_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"permission_groups_unique_name\" UNIQUE (\"name\")\
);",
        },
        [13] = {
            kind = "createTable",
            persistentId = "postgres.permissions",
            sql = "CREATE TABLE \"public\".\"permissions\"\
(\
    \"id\" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text NOT NULL,\
    CONSTRAINT \"permissions_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"permissions_unique_name\" UNIQUE (\"name\")\
);",
        },
        [14] = {
            kind = "createTable",
            persistentId = "postgres.permission_group_data",
            sql = "CREATE TABLE \"public\".\"permission_group_data\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"group_id\" smallint NOT NULL,\
    \"permission_id\" smallint NOT NULL,\
    CONSTRAINT \"permission_group_data_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"permission_group_data_key\" UNIQUE (\"group_id\", \"permission_id\"),\
    CONSTRAINT \"permission_group_data_group_fk\" FOREIGN KEY (\"group_id\") REFERENCES \"public\".\"permission_groups\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE,\
    CONSTRAINT \"permission_group_data_permission_fk\" FOREIGN KEY (\"permission_id\") REFERENCES \"public\".\"permissions\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);",
        },
        [15] = {
            kind = "createTable",
            persistentId = "postgres.proximity_triggers",
            sql = "CREATE TABLE \"public\".\"proximity_triggers\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text DEFAULT '' NOT NULL,\
    \"flags\" smallint DEFAULT 0 NOT NULL,\
    \"map_id\" integer DEFAULT 0 NOT NULL,\
    \"position_x\" real DEFAULT 0.0 NOT NULL,\
    \"position_y\" real DEFAULT 0.0 NOT NULL,\
    \"position_z\" real DEFAULT 0.0 NOT NULL,\
    \"extents_x\" real DEFAULT 1.0 NOT NULL,\
    \"extents_y\" real DEFAULT 1.0 NOT NULL,\
    \"extents_z\" real DEFAULT 1.0 NOT NULL,\
    CONSTRAINT \"proximity_triggers_pkey\" PRIMARY KEY (\"id\")\
);",
        },
        [16] = {
            kind = "createTable",
            persistentId = "postgres.spell_effects",
            sql = "CREATE TABLE \"public\".\"spell_effects\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"spell_id\" integer NOT NULL,\
    \"effect_priority\" smallint DEFAULT 0 NOT NULL,\
    \"effect_type\" smallint NOT NULL,\
    \"effect_value_1\" integer DEFAULT 0 NOT NULL,\
    \"effect_value_2\" integer DEFAULT 0 NOT NULL,\
    \"effect_value_3\" integer DEFAULT 0 NOT NULL,\
    \"effect_misc_value_1\" integer DEFAULT 0 NOT NULL,\
    \"effect_misc_value_2\" integer DEFAULT 0 NOT NULL,\
    \"effect_misc_value_3\" integer DEFAULT 0 NOT NULL,\
    CONSTRAINT \"spell_effects_pkey\" PRIMARY KEY (\"id\")\
);",
        },
        [17] = {
            kind = "createTable",
            persistentId = "postgres.spell_proc_data",
            sql = "CREATE TABLE \"public\".\"spell_proc_data\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"phase_mask\" integer DEFAULT -1 NOT NULL,\
    \"type_mask\" bigint DEFAULT -1 NOT NULL,\
    \"hit_mask\" bigint DEFAULT -1 NOT NULL,\
    \"flags\" bigint DEFAULT 0 NOT NULL,\
    \"procs_per_min\" real DEFAULT 1.0 NOT NULL,\
    \"chance_to_proc\" real DEFAULT 0.0 NOT NULL,\
    \"internal_cooldown_ms\" integer DEFAULT 0 NOT NULL,\
    \"charges\" integer DEFAULT -1 NOT NULL,\
    CONSTRAINT \"spell_proc_data_pkey\" PRIMARY KEY (\"id\")\
);",
        },
        [18] = {
            kind = "createTable",
            persistentId = "postgres.spell_proc_link",
            sql = "CREATE TABLE \"public\".\"spell_proc_link\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"spell_id\" integer NOT NULL,\
    \"effect_mask\" bigint DEFAULT -1 NOT NULL,\
    \"proc_data_id\" integer NOT NULL,\
    CONSTRAINT \"spell_proc_link_pkey\" PRIMARY KEY (\"id\")\
);",
        },
        [19] = {
            kind = "createTable",
            persistentId = "postgres.spells",
            sql = "CREATE TABLE \"public\".\"spells\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text DEFAULT '' NOT NULL,\
    \"description\" text DEFAULT '' NOT NULL,\
    \"aura_description\" text DEFAULT '' NOT NULL,\
    \"icon_id\" integer DEFAULT 0 NOT NULL,\
    \"cast_time\" real DEFAULT 0.0 NOT NULL,\
    \"cooldown\" real DEFAULT 0.0 NOT NULL,\
    \"duration\" real DEFAULT 0.0 NOT NULL,\
    CONSTRAINT \"spells_pkey\" PRIMARY KEY (\"id\")\
);",
        },
        [20] = {
            kind = "addIndex",
            persistentId = "postgres.creatures.map_id_idx",
            sql = "CREATE INDEX \"creatures_map_id_idx\" ON \"public\".\"creatures\" (\"map_id\" ASC);",
        },
        [21] = {
            kind = "addIndex",
            persistentId = "postgres.proximity_triggers.map_id_idx",
            sql = "CREATE INDEX \"proximity_triggers_map_id_idx\" ON \"public\".\"proximity_triggers\" (\"map_id\" ASC);",
        },
    },
    parentHash = "c2de88a25500eab16c313c2122d978970ee18b014d8523097415f8832106bdfa",
    sql = "BEGIN;\
CREATE SCHEMA IF NOT EXISTS \"public\";\
CREATE TABLE \"public\".\"creature_templates\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"flags\" integer DEFAULT 0 NOT NULL,\
    \"name\" text DEFAULT 'Unknown' NOT NULL,\
    \"subname\" text DEFAULT '' NOT NULL,\
    \"display_id\" integer DEFAULT 0 NOT NULL,\
    \"scale\" real DEFAULT 1.0 NOT NULL,\
    \"min_level\" smallint DEFAULT 1 NOT NULL,\
    \"max_level\" smallint DEFAULT 1 NOT NULL,\
    \"armor_mod\" real DEFAULT 1.0 NOT NULL,\
    \"health_mod\" real DEFAULT 1.0 NOT NULL,\
    \"resource_mod\" real DEFAULT 1.0 NOT NULL,\
    \"damage_mod\" real DEFAULT 1.0 NOT NULL,\
    \"script_name\" text DEFAULT '' NOT NULL,\
    CONSTRAINT \"creature_templates_pkey\" PRIMARY KEY (\"id\")\
);\
CREATE TABLE \"public\".\"creatures\"\
(\
    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"template_id\" integer NOT NULL,\
    \"display_id\" integer NOT NULL,\
    \"map_id\" integer NOT NULL,\
    \"position_x\" real NOT NULL,\
    \"position_y\" real NOT NULL,\
    \"position_z\" real NOT NULL,\
    \"position_o\" real NOT NULL,\
    \"script_name\" text DEFAULT '' NOT NULL,\
    CONSTRAINT \"creatures_pkey\" PRIMARY KEY (\"id\")\
);\
CREATE TABLE \"public\".\"currency\"\
(\
    \"id\" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text NOT NULL,\
    CONSTRAINT \"currency_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"currency_unique_name\" UNIQUE (\"name\")\
);\
CREATE TABLE \"public\".\"item_armor_templates\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"equip_type\" smallint DEFAULT 0 NOT NULL,\
    \"bonus_armor\" integer DEFAULT 0 NOT NULL,\
    CONSTRAINT \"item_armor_templates_pkey\" PRIMARY KEY (\"id\")\
);\
CREATE TABLE \"public\".\"item_shield_templates\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"bonus_armor\" integer DEFAULT 0 NOT NULL,\
    \"block\" integer DEFAULT 0 NOT NULL,\
    CONSTRAINT \"item_shield_templates_pkey\" PRIMARY KEY (\"id\")\
);\
CREATE TABLE \"public\".\"item_stat_templates\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"stat_type_1\" smallint DEFAULT 0 NOT NULL,\
    \"stat_type_2\" smallint DEFAULT 0 NOT NULL,\
    \"stat_type_3\" smallint DEFAULT 0 NOT NULL,\
    \"stat_type_4\" smallint DEFAULT 0 NOT NULL,\
    \"stat_type_5\" smallint DEFAULT 0 NOT NULL,\
    \"stat_type_6\" smallint DEFAULT 0 NOT NULL,\
    \"stat_type_7\" smallint DEFAULT 0 NOT NULL,\
    \"stat_type_8\" smallint DEFAULT 0 NOT NULL,\
    \"stat_value_1\" integer DEFAULT 0 NOT NULL,\
    \"stat_value_2\" integer DEFAULT 0 NOT NULL,\
    \"stat_value_3\" integer DEFAULT 0 NOT NULL,\
    \"stat_value_4\" integer DEFAULT 0 NOT NULL,\
    \"stat_value_5\" integer DEFAULT 0 NOT NULL,\
    \"stat_value_6\" integer DEFAULT 0 NOT NULL,\
    \"stat_value_7\" integer DEFAULT 0 NOT NULL,\
    \"stat_value_8\" integer DEFAULT 0 NOT NULL,\
    CONSTRAINT \"item_stat_templates_pkey\" PRIMARY KEY (\"id\")\
);\
CREATE TABLE \"public\".\"item_templates\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"display_id\" integer DEFAULT 0 NOT NULL,\
    \"bind\" smallint DEFAULT 0 NOT NULL,\
    \"rarity\" smallint DEFAULT 0 NOT NULL,\
    \"category\" smallint DEFAULT 1 NOT NULL,\
    \"type\" smallint DEFAULT 1 NOT NULL,\
    \"virtual_level\" smallint DEFAULT 0 NOT NULL,\
    \"required_level\" smallint DEFAULT 0 NOT NULL,\
    \"durability\" integer DEFAULT 0 NOT NULL,\
    \"icon_id\" integer DEFAULT 0 NOT NULL,\
    \"name\" text NOT NULL,\
    \"description\" text DEFAULT '' NOT NULL,\
    \"armor\" integer DEFAULT 0 NOT NULL,\
    \"stat_template_id\" integer DEFAULT 0 NOT NULL,\
    \"armor_template_id\" integer DEFAULT 0 NOT NULL,\
    \"weapon_template_id\" integer DEFAULT 0 NOT NULL,\
    \"shield_template_id\" integer DEFAULT 0 NOT NULL,\
    CONSTRAINT \"item_templates_pkey\" PRIMARY KEY (\"id\")\
);\
CREATE TABLE \"public\".\"item_weapon_templates\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"weapon_style\" smallint DEFAULT 0 NOT NULL,\
    \"min_damage\" integer DEFAULT 0 NOT NULL,\
    \"max_damage\" integer DEFAULT 0 NOT NULL,\
    \"speed\" real DEFAULT 1.0 NOT NULL,\
    CONSTRAINT \"item_weapon_templates_pkey\" PRIMARY KEY (\"id\")\
);\
CREATE TABLE \"public\".\"maps\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"flags\" integer DEFAULT 0 NOT NULL,\
    \"internal_name\" text DEFAULT '' NOT NULL,\
    \"name\" text DEFAULT '' NOT NULL,\
    \"type\" smallint DEFAULT 0 NOT NULL,\
    \"max_players\" smallint DEFAULT 0 NOT NULL,\
    CONSTRAINT \"maps_pkey\" PRIMARY KEY (\"id\")\
);\
CREATE TABLE \"public\".\"map_locations\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text DEFAULT '' NOT NULL,\
    \"map_id\" integer NOT NULL,\
    \"position_x\" real DEFAULT 0.0 NOT NULL,\
    \"position_y\" real DEFAULT 0.0 NOT NULL,\
    \"position_z\" real DEFAULT 0.0 NOT NULL,\
    \"position_o\" real DEFAULT 0.0 NOT NULL,\
    CONSTRAINT \"map_locations_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"map_locations_map_fk\" FOREIGN KEY (\"map_id\") REFERENCES \"public\".\"maps\" (\"id\") ON UPDATE NO ACTION ON DELETE NO ACTION\
);\
CREATE TABLE \"public\".\"permission_groups\"\
(\
    \"id\" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text NOT NULL,\
    CONSTRAINT \"permission_groups_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"permission_groups_unique_name\" UNIQUE (\"name\")\
);\
CREATE TABLE \"public\".\"permissions\"\
(\
    \"id\" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text NOT NULL,\
    CONSTRAINT \"permissions_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"permissions_unique_name\" UNIQUE (\"name\")\
);\
CREATE TABLE \"public\".\"permission_group_data\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"group_id\" smallint NOT NULL,\
    \"permission_id\" smallint NOT NULL,\
    CONSTRAINT \"permission_group_data_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"permission_group_data_key\" UNIQUE (\"group_id\", \"permission_id\"),\
    CONSTRAINT \"permission_group_data_group_fk\" FOREIGN KEY (\"group_id\") REFERENCES \"public\".\"permission_groups\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE,\
    CONSTRAINT \"permission_group_data_permission_fk\" FOREIGN KEY (\"permission_id\") REFERENCES \"public\".\"permissions\" (\"id\") ON UPDATE NO ACTION ON DELETE CASCADE\
);\
CREATE TABLE \"public\".\"proximity_triggers\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text DEFAULT '' NOT NULL,\
    \"flags\" smallint DEFAULT 0 NOT NULL,\
    \"map_id\" integer DEFAULT 0 NOT NULL,\
    \"position_x\" real DEFAULT 0.0 NOT NULL,\
    \"position_y\" real DEFAULT 0.0 NOT NULL,\
    \"position_z\" real DEFAULT 0.0 NOT NULL,\
    \"extents_x\" real DEFAULT 1.0 NOT NULL,\
    \"extents_y\" real DEFAULT 1.0 NOT NULL,\
    \"extents_z\" real DEFAULT 1.0 NOT NULL,\
    CONSTRAINT \"proximity_triggers_pkey\" PRIMARY KEY (\"id\")\
);\
CREATE TABLE \"public\".\"spell_effects\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"spell_id\" integer NOT NULL,\
    \"effect_priority\" smallint DEFAULT 0 NOT NULL,\
    \"effect_type\" smallint NOT NULL,\
    \"effect_value_1\" integer DEFAULT 0 NOT NULL,\
    \"effect_value_2\" integer DEFAULT 0 NOT NULL,\
    \"effect_value_3\" integer DEFAULT 0 NOT NULL,\
    \"effect_misc_value_1\" integer DEFAULT 0 NOT NULL,\
    \"effect_misc_value_2\" integer DEFAULT 0 NOT NULL,\
    \"effect_misc_value_3\" integer DEFAULT 0 NOT NULL,\
    CONSTRAINT \"spell_effects_pkey\" PRIMARY KEY (\"id\")\
);\
CREATE TABLE \"public\".\"spell_proc_data\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"phase_mask\" integer DEFAULT -1 NOT NULL,\
    \"type_mask\" bigint DEFAULT -1 NOT NULL,\
    \"hit_mask\" bigint DEFAULT -1 NOT NULL,\
    \"flags\" bigint DEFAULT 0 NOT NULL,\
    \"procs_per_min\" real DEFAULT 1.0 NOT NULL,\
    \"chance_to_proc\" real DEFAULT 0.0 NOT NULL,\
    \"internal_cooldown_ms\" integer DEFAULT 0 NOT NULL,\
    \"charges\" integer DEFAULT -1 NOT NULL,\
    CONSTRAINT \"spell_proc_data_pkey\" PRIMARY KEY (\"id\")\
);\
CREATE TABLE \"public\".\"spell_proc_link\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"spell_id\" integer NOT NULL,\
    \"effect_mask\" bigint DEFAULT -1 NOT NULL,\
    \"proc_data_id\" integer NOT NULL,\
    CONSTRAINT \"spell_proc_link_pkey\" PRIMARY KEY (\"id\")\
);\
CREATE TABLE \"public\".\"spells\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text DEFAULT '' NOT NULL,\
    \"description\" text DEFAULT '' NOT NULL,\
    \"aura_description\" text DEFAULT '' NOT NULL,\
    \"icon_id\" integer DEFAULT 0 NOT NULL,\
    \"cast_time\" real DEFAULT 0.0 NOT NULL,\
    \"cooldown\" real DEFAULT 0.0 NOT NULL,\
    \"duration\" real DEFAULT 0.0 NOT NULL,\
    CONSTRAINT \"spells_pkey\" PRIMARY KEY (\"id\")\
);\
CREATE INDEX \"creatures_map_id_idx\" ON \"public\".\"creatures\" (\"map_id\" ASC);\
CREATE INDEX \"proximity_triggers_map_id_idx\" ON \"public\".\"proximity_triggers\" (\"map_id\" ASC);\
COMMIT;\
",
    targetHash = "85f1c244e559f033f7c4eadc017527ead4fbe76ff10a5c8bd5ba94a17433a5e7",
    transactional = true,
}
