-- MetaGen PostgreSQL history. Review and commit this file.
return {
    bundle = "world",
    contentHash = "648b414bffc160c5bbf938446c404a16dfd6b4ac52fe26652a0d50ef59125fe4",
    id = "0002_add_creature_import_fields",
    name = "add_creature_import_fields",
    operations = {
        [1] = {
            kind = "createTable",
            persistentId = "postgres.creature_class_level_stats",
            sql = "CREATE TABLE \"public\".\"creature_class_level_stats\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"unit_class\" smallint NOT NULL,\
    \"level\" smallint NOT NULL,\
    \"health\" integer NOT NULL,\
    \"resource\" integer NOT NULL,\
    \"armor\" integer NOT NULL,\
    \"damage\" real NOT NULL,\
    CONSTRAINT \"creature_class_level_stats_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"creature_class_level_stats_class_level_key\" UNIQUE (\"unit_class\", \"level\")\
);",
        },
        [2] = {
            kind = "addColumn",
            persistentId = "postgres.creature_templates.creature_type",
            sql = "ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"creature_type\" smallint DEFAULT 0 NOT NULL;",
        },
        [3] = {
            kind = "addColumn",
            persistentId = "postgres.creature_templates.damage_school",
            sql = "ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"damage_school\" smallint DEFAULT 0 NOT NULL;",
        },
        [4] = {
            kind = "addColumn",
            persistentId = "postgres.creature_templates.default_movement_type",
            sql = "ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"default_movement_type\" smallint DEFAULT 0 NOT NULL;",
        },
        [5] = {
            kind = "addColumn",
            persistentId = "postgres.creature_templates.detection_range",
            sql = "ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"detection_range\" real DEFAULT 20.0 NOT NULL;",
        },
        [6] = {
            kind = "addColumn",
            persistentId = "postgres.creature_templates.experience_mod",
            sql = "ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"experience_mod\" real DEFAULT 1.0 NOT NULL;",
        },
        [7] = {
            kind = "addColumn",
            persistentId = "postgres.creature_templates.faction_id",
            sql = "ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"faction_id\" smallint DEFAULT 0 NOT NULL;",
        },
        [8] = {
            kind = "addColumn",
            persistentId = "postgres.creature_templates.leash_range",
            sql = "ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"leash_range\" real DEFAULT 0.0 NOT NULL;",
        },
        [9] = {
            kind = "addColumn",
            persistentId = "postgres.creature_templates.melee_attack_time_ms",
            sql = "ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"melee_attack_time_ms\" integer DEFAULT 2000 NOT NULL;",
        },
        [10] = {
            kind = "addColumn",
            persistentId = "postgres.creature_templates.rank",
            sql = "ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"rank\" smallint DEFAULT 0 NOT NULL;",
        },
        [11] = {
            kind = "addColumn",
            persistentId = "postgres.creature_templates.run_speed_mod",
            sql = "ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"run_speed_mod\" real DEFAULT 1.0 NOT NULL;",
        },
        [12] = {
            kind = "addColumn",
            persistentId = "postgres.creature_templates.unit_class",
            sql = "ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"unit_class\" smallint DEFAULT 1 NOT NULL;",
        },
        [13] = {
            kind = "addColumn",
            persistentId = "postgres.creature_templates.walk_speed_mod",
            sql = "ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"walk_speed_mod\" real DEFAULT 1.0 NOT NULL;",
        },
        [14] = {
            kind = "addColumn",
            persistentId = "postgres.creatures.movement_type",
            sql = "ALTER TABLE \"public\".\"creatures\" ADD COLUMN \"movement_type\" smallint DEFAULT 0 NOT NULL;",
        },
        [15] = {
            kind = "addColumn",
            persistentId = "postgres.creatures.spawn_time_in_sec_max",
            sql = "ALTER TABLE \"public\".\"creatures\" ADD COLUMN \"spawn_time_in_sec_max\" integer DEFAULT 120 NOT NULL;",
        },
        [16] = {
            kind = "addColumn",
            persistentId = "postgres.creatures.spawn_time_in_sec_min",
            sql = "ALTER TABLE \"public\".\"creatures\" ADD COLUMN \"spawn_time_in_sec_min\" integer DEFAULT 120 NOT NULL;",
        },
        [17] = {
            kind = "addColumn",
            persistentId = "postgres.creatures.wander_distance",
            sql = "ALTER TABLE \"public\".\"creatures\" ADD COLUMN \"wander_distance\" real DEFAULT 5.0 NOT NULL;",
        },
    },
    parentHash = "85f1c244e559f033f7c4eadc017527ead4fbe76ff10a5c8bd5ba94a17433a5e7",
    sql = "BEGIN;\
CREATE TABLE \"public\".\"creature_class_level_stats\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"unit_class\" smallint NOT NULL,\
    \"level\" smallint NOT NULL,\
    \"health\" integer NOT NULL,\
    \"resource\" integer NOT NULL,\
    \"armor\" integer NOT NULL,\
    \"damage\" real NOT NULL,\
    CONSTRAINT \"creature_class_level_stats_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"creature_class_level_stats_class_level_key\" UNIQUE (\"unit_class\", \"level\")\
);\
ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"creature_type\" smallint DEFAULT 0 NOT NULL;\
ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"damage_school\" smallint DEFAULT 0 NOT NULL;\
ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"default_movement_type\" smallint DEFAULT 0 NOT NULL;\
ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"detection_range\" real DEFAULT 20.0 NOT NULL;\
ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"experience_mod\" real DEFAULT 1.0 NOT NULL;\
ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"faction_id\" smallint DEFAULT 0 NOT NULL;\
ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"leash_range\" real DEFAULT 0.0 NOT NULL;\
ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"melee_attack_time_ms\" integer DEFAULT 2000 NOT NULL;\
ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"rank\" smallint DEFAULT 0 NOT NULL;\
ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"run_speed_mod\" real DEFAULT 1.0 NOT NULL;\
ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"unit_class\" smallint DEFAULT 1 NOT NULL;\
ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"walk_speed_mod\" real DEFAULT 1.0 NOT NULL;\
ALTER TABLE \"public\".\"creatures\" ADD COLUMN \"movement_type\" smallint DEFAULT 0 NOT NULL;\
ALTER TABLE \"public\".\"creatures\" ADD COLUMN \"spawn_time_in_sec_max\" integer DEFAULT 120 NOT NULL;\
ALTER TABLE \"public\".\"creatures\" ADD COLUMN \"spawn_time_in_sec_min\" integer DEFAULT 120 NOT NULL;\
ALTER TABLE \"public\".\"creatures\" ADD COLUMN \"wander_distance\" real DEFAULT 5.0 NOT NULL;\
COMMIT;\
",
    targetHash = "3bb27092864fdecadd92c0b83014affd6b3d9b416da475a9dc2b2d00472e6a08",
    transactional = true,
}
