-- MetaGen PostgreSQL history. Review and commit this file.
return {
    bundle = "world",
    contentHash = "ccb9c6958f74a538214657ad098b925ce0a0cddd9e25d4b982dce3138e36117d",
    id = "0004_add_faction_system",
    name = "add_faction_system",
    operations = {
        [1] = {
            kind = "createTable",
            persistentId = "postgres.factions",
            sql = "CREATE TABLE \"public\".\"factions\"\
(\
    \"id\" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text NOT NULL,\
    \"flags\" smallint DEFAULT 0 NOT NULL,\
    \"default_reaction_to_others\" smallint DEFAULT 2 NOT NULL,\
    \"default_player_reaction_min\" smallint DEFAULT 0 NOT NULL,\
    \"default_player_reaction_max\" smallint DEFAULT 3 NOT NULL,\
    \"default_reputation_value\" integer DEFAULT 0 NOT NULL,\
    CONSTRAINT \"factions_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"factions_unique_name\" UNIQUE (\"name\")\
);",
        },
        [2] = {
            kind = "createTable",
            persistentId = "postgres.faction_relations",
            sql = "CREATE TABLE \"public\".\"faction_relations\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"source_faction_id\" smallint NOT NULL,\
    \"target_faction_id\" smallint NOT NULL,\
    \"reaction\" smallint NOT NULL,\
    CONSTRAINT \"faction_relations_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"faction_relations_source_target_key\" UNIQUE (\"source_faction_id\", \"target_faction_id\"),\
    CONSTRAINT \"faction_relations_source_faction_fk\" FOREIGN KEY (\"source_faction_id\") REFERENCES \"public\".\"factions\" (\"id\") ON UPDATE NO ACTION ON DELETE NO ACTION,\
    CONSTRAINT \"faction_relations_target_faction_fk\" FOREIGN KEY (\"target_faction_id\") REFERENCES \"public\".\"factions\" (\"id\") ON UPDATE NO ACTION ON DELETE NO ACTION\
);",
        },
        [3] = {
            kind = "createTable",
            persistentId = "postgres.faction_standings",
            sql = "CREATE TABLE \"public\".\"faction_standings\"\
(\
    \"id\" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text NOT NULL,\
    \"minimum_value\" integer NOT NULL,\
    \"reaction\" smallint NOT NULL,\
    \"sort_order\" smallint NOT NULL,\
    CONSTRAINT \"faction_standings_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"faction_standings_unique_name\" UNIQUE (\"name\"),\
    CONSTRAINT \"faction_standings_unique_sort_order\" UNIQUE (\"sort_order\")\
);",
        },
        [4] = {
            kind = "createTable",
            persistentId = "postgres.faction_starting_reputations",
            sql = "CREATE TABLE \"public\".\"faction_starting_reputations\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"player_faction_id\" smallint NOT NULL,\
    \"target_faction_id\" smallint NOT NULL,\
    \"value\" integer NOT NULL,\
    CONSTRAINT \"faction_starting_reputations_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"faction_starting_reputations_player_target_key\" UNIQUE (\"player_faction_id\", \"target_faction_id\"),\
    CONSTRAINT \"faction_starting_reputations_player_faction_fk\" FOREIGN KEY (\"player_faction_id\") REFERENCES \"public\".\"factions\" (\"id\") ON UPDATE NO ACTION ON DELETE NO ACTION,\
    CONSTRAINT \"faction_starting_reputations_target_faction_fk\" FOREIGN KEY (\"target_faction_id\") REFERENCES \"public\".\"factions\" (\"id\") ON UPDATE NO ACTION ON DELETE NO ACTION\
);",
        },
        [5] = {
            kind = "createTable",
            persistentId = "postgres.unit_race_factions",
            sql = "CREATE TABLE \"public\".\"unit_race_factions\"\
(\
    \"race_id\" smallint NOT NULL,\
    \"faction_id\" smallint NOT NULL,\
    CONSTRAINT \"unit_race_factions_race_key\" UNIQUE (\"race_id\"),\
    CONSTRAINT \"unit_race_factions_faction_fk\" FOREIGN KEY (\"faction_id\") REFERENCES \"public\".\"factions\" (\"id\") ON UPDATE NO ACTION ON DELETE NO ACTION\
);",
        },
        [6] = {
            kind = "addColumn",
            persistentId = "postgres.creature_templates.player_reaction_min_override",
            sql = "ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"player_reaction_min_override\" smallint DEFAULT 255 NOT NULL;",
        },
        [7] = {
            kind = "addColumn",
            persistentId = "postgres.creature_templates.player_reaction_max_override",
            sql = "ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"player_reaction_max_override\" smallint DEFAULT 255 NOT NULL;",
        },
    },
    parentHash = "73f9f6c438618662fef32b5b414bee5d3b9f9daf8feb2bc54221f04afe75ade1",
    sql = "BEGIN;\
CREATE TABLE \"public\".\"factions\"\
(\
    \"id\" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text NOT NULL,\
    \"flags\" smallint DEFAULT 0 NOT NULL,\
    \"default_reaction_to_others\" smallint DEFAULT 2 NOT NULL,\
    \"default_player_reaction_min\" smallint DEFAULT 0 NOT NULL,\
    \"default_player_reaction_max\" smallint DEFAULT 3 NOT NULL,\
    \"default_reputation_value\" integer DEFAULT 0 NOT NULL,\
    CONSTRAINT \"factions_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"factions_unique_name\" UNIQUE (\"name\")\
);\
CREATE TABLE \"public\".\"faction_relations\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"source_faction_id\" smallint NOT NULL,\
    \"target_faction_id\" smallint NOT NULL,\
    \"reaction\" smallint NOT NULL,\
    CONSTRAINT \"faction_relations_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"faction_relations_source_target_key\" UNIQUE (\"source_faction_id\", \"target_faction_id\"),\
    CONSTRAINT \"faction_relations_source_faction_fk\" FOREIGN KEY (\"source_faction_id\") REFERENCES \"public\".\"factions\" (\"id\") ON UPDATE NO ACTION ON DELETE NO ACTION,\
    CONSTRAINT \"faction_relations_target_faction_fk\" FOREIGN KEY (\"target_faction_id\") REFERENCES \"public\".\"factions\" (\"id\") ON UPDATE NO ACTION ON DELETE NO ACTION\
);\
CREATE TABLE \"public\".\"faction_standings\"\
(\
    \"id\" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"name\" text NOT NULL,\
    \"minimum_value\" integer NOT NULL,\
    \"reaction\" smallint NOT NULL,\
    \"sort_order\" smallint NOT NULL,\
    CONSTRAINT \"faction_standings_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"faction_standings_unique_name\" UNIQUE (\"name\"),\
    CONSTRAINT \"faction_standings_unique_sort_order\" UNIQUE (\"sort_order\")\
);\
CREATE TABLE \"public\".\"faction_starting_reputations\"\
(\
    \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,\
    \"player_faction_id\" smallint NOT NULL,\
    \"target_faction_id\" smallint NOT NULL,\
    \"value\" integer NOT NULL,\
    CONSTRAINT \"faction_starting_reputations_pkey\" PRIMARY KEY (\"id\"),\
    CONSTRAINT \"faction_starting_reputations_player_target_key\" UNIQUE (\"player_faction_id\", \"target_faction_id\"),\
    CONSTRAINT \"faction_starting_reputations_player_faction_fk\" FOREIGN KEY (\"player_faction_id\") REFERENCES \"public\".\"factions\" (\"id\") ON UPDATE NO ACTION ON DELETE NO ACTION,\
    CONSTRAINT \"faction_starting_reputations_target_faction_fk\" FOREIGN KEY (\"target_faction_id\") REFERENCES \"public\".\"factions\" (\"id\") ON UPDATE NO ACTION ON DELETE NO ACTION\
);\
CREATE TABLE \"public\".\"unit_race_factions\"\
(\
    \"race_id\" smallint NOT NULL,\
    \"faction_id\" smallint NOT NULL,\
    CONSTRAINT \"unit_race_factions_race_key\" UNIQUE (\"race_id\"),\
    CONSTRAINT \"unit_race_factions_faction_fk\" FOREIGN KEY (\"faction_id\") REFERENCES \"public\".\"factions\" (\"id\") ON UPDATE NO ACTION ON DELETE NO ACTION\
);\
ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"player_reaction_min_override\" smallint DEFAULT 255 NOT NULL;\
ALTER TABLE \"public\".\"creature_templates\" ADD COLUMN \"player_reaction_max_override\" smallint DEFAULT 255 NOT NULL;\
COMMIT;\
",
    targetHash = "8ed32cbdd1160252bdef8f511e8d88f3f38d086f16e9bb487edb42e1803830ef",
    transactional = true,
}
