-- MetaGen PostgreSQL history. Review and commit this file.
return {
    bundle = "world",
    format = 3,
    hash = "85f1c244e559f033f7c4eadc017527ead4fbe76ff10a5c8bd5ba94a17433a5e7",
    schemas = {
        public = true,
    },
    tables = {
        ["postgres.creature_templates"] = {
            constraints = {
            },
            fields = {
                ["postgres.creature_templates.armor_mod"] = {
                    columnName = "armor_mod",
                    defaultValue = 1.0,
                    hasDefault = true,
                    nullable = false,
                    order = 9,
                    persistentId = "postgres.creature_templates.armor_mod",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.creature_templates.damage_mod"] = {
                    columnName = "damage_mod",
                    defaultValue = 1.0,
                    hasDefault = true,
                    nullable = false,
                    order = 12,
                    persistentId = "postgres.creature_templates.damage_mod",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.creature_templates.display_id"] = {
                    columnName = "display_id",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 5,
                    persistentId = "postgres.creature_templates.display_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.creature_templates.flags"] = {
                    columnName = "flags",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.creature_templates.flags",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.creature_templates.health_mod"] = {
                    columnName = "health_mod",
                    defaultValue = 1.0,
                    hasDefault = true,
                    nullable = false,
                    order = 10,
                    persistentId = "postgres.creature_templates.health_mod",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.creature_templates.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.creature_templates.id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.creature_templates.max_level"] = {
                    columnName = "max_level",
                    defaultValue = 1,
                    hasDefault = true,
                    nullable = false,
                    order = 8,
                    persistentId = "postgres.creature_templates.max_level",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.creature_templates.min_level"] = {
                    columnName = "min_level",
                    defaultValue = 1,
                    hasDefault = true,
                    nullable = false,
                    order = 7,
                    persistentId = "postgres.creature_templates.min_level",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.creature_templates.name"] = {
                    columnName = "name",
                    defaultValue = "Unknown",
                    hasDefault = true,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.creature_templates.name",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
                ["postgres.creature_templates.resource_mod"] = {
                    columnName = "resource_mod",
                    defaultValue = 1.0,
                    hasDefault = true,
                    nullable = false,
                    order = 11,
                    persistentId = "postgres.creature_templates.resource_mod",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.creature_templates.scale"] = {
                    columnName = "scale",
                    defaultValue = 1.0,
                    hasDefault = true,
                    nullable = false,
                    order = 6,
                    persistentId = "postgres.creature_templates.scale",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.creature_templates.script_name"] = {
                    columnName = "script_name",
                    defaultValue = "",
                    hasDefault = true,
                    nullable = false,
                    order = 13,
                    persistentId = "postgres.creature_templates.script_name",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
                ["postgres.creature_templates.subname"] = {
                    columnName = "subname",
                    defaultValue = "",
                    hasDefault = true,
                    nullable = false,
                    order = 4,
                    persistentId = "postgres.creature_templates.subname",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.creature_templates",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.creature_templates.id",
                    },
                },
                name = "creature_templates_pkey",
                persistentId = "postgres.creature_templates.pk",
                signature = "creature_templates_pkey|postgres.creature_templates.id:asc",
            },
            schema = "public",
            tableName = "creature_templates",
        },
        ["postgres.creatures"] = {
            constraints = {
            },
            fields = {
                ["postgres.creatures.display_id"] = {
                    columnName = "display_id",
                    hasDefault = false,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.creatures.display_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.creatures.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.creatures.id",
                    postgresType = {
                        name = "bigint",
                        sql = "bigint",
                    },
                },
                ["postgres.creatures.map_id"] = {
                    columnName = "map_id",
                    hasDefault = false,
                    nullable = false,
                    order = 4,
                    persistentId = "postgres.creatures.map_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.creatures.position_o"] = {
                    columnName = "position_o",
                    hasDefault = false,
                    nullable = false,
                    order = 8,
                    persistentId = "postgres.creatures.position_o",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.creatures.position_x"] = {
                    columnName = "position_x",
                    hasDefault = false,
                    nullable = false,
                    order = 5,
                    persistentId = "postgres.creatures.position_x",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.creatures.position_y"] = {
                    columnName = "position_y",
                    hasDefault = false,
                    nullable = false,
                    order = 6,
                    persistentId = "postgres.creatures.position_y",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.creatures.position_z"] = {
                    columnName = "position_z",
                    hasDefault = false,
                    nullable = false,
                    order = 7,
                    persistentId = "postgres.creatures.position_z",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.creatures.script_name"] = {
                    columnName = "script_name",
                    defaultValue = "",
                    hasDefault = true,
                    nullable = false,
                    order = 9,
                    persistentId = "postgres.creatures.script_name",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
                ["postgres.creatures.template_id"] = {
                    columnName = "template_id",
                    hasDefault = false,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.creatures.template_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
            },
            indexes = {
                ["postgres.creatures.map_id_idx"] = {
                    fields = {
                        [1] = {
                            columnName = "map_id",
                            direction = "asc",
                            persistentId = "postgres.creatures.map_id",
                        },
                    },
                    name = "creatures_map_id_idx",
                    persistentId = "postgres.creatures.map_id_idx",
                    signature = "creatures_map_id_idx|false|postgres.creatures.map_id:asc",
                    unique = false,
                },
            },
            persistentId = "postgres.creatures",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.creatures.id",
                    },
                },
                name = "creatures_pkey",
                persistentId = "postgres.creatures.pk",
                signature = "creatures_pkey|postgres.creatures.id:asc",
            },
            schema = "public",
            tableName = "creatures",
        },
        ["postgres.currency"] = {
            constraints = {
                ["postgres.currency.currency_unique_name"] = {
                    kind = "unique",
                    name = "currency_unique_name",
                    persistentId = "postgres.currency.currency_unique_name",
                    signature = "unique|currency_unique_name|postgres.currency.name:asc||nil:nil|||||",
                },
            },
            fields = {
                ["postgres.currency.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.currency.id",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.currency.name"] = {
                    columnName = "name",
                    hasDefault = false,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.currency.name",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.currency",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.currency.id",
                    },
                },
                name = "currency_pkey",
                persistentId = "postgres.currency.pk",
                signature = "currency_pkey|postgres.currency.id:asc",
            },
            schema = "public",
            tableName = "currency",
        },
        ["postgres.item_armor_templates"] = {
            constraints = {
            },
            fields = {
                ["postgres.item_armor_templates.bonus_armor"] = {
                    columnName = "bonus_armor",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.item_armor_templates.bonus_armor",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_armor_templates.equip_type"] = {
                    columnName = "equip_type",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.item_armor_templates.equip_type",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_armor_templates.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.item_armor_templates.id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.item_armor_templates",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.item_armor_templates.id",
                    },
                },
                name = "item_armor_templates_pkey",
                persistentId = "postgres.item_armor_templates.pk",
                signature = "item_armor_templates_pkey|postgres.item_armor_templates.id:asc",
            },
            schema = "public",
            tableName = "item_armor_templates",
        },
        ["postgres.item_shield_templates"] = {
            constraints = {
            },
            fields = {
                ["postgres.item_shield_templates.block"] = {
                    columnName = "block",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.item_shield_templates.block",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_shield_templates.bonus_armor"] = {
                    columnName = "bonus_armor",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.item_shield_templates.bonus_armor",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_shield_templates.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.item_shield_templates.id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.item_shield_templates",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.item_shield_templates.id",
                    },
                },
                name = "item_shield_templates_pkey",
                persistentId = "postgres.item_shield_templates.pk",
                signature = "item_shield_templates_pkey|postgres.item_shield_templates.id:asc",
            },
            schema = "public",
            tableName = "item_shield_templates",
        },
        ["postgres.item_stat_templates"] = {
            constraints = {
            },
            fields = {
                ["postgres.item_stat_templates.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.item_stat_templates.id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_stat_templates.stat_type_1"] = {
                    columnName = "stat_type_1",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.item_stat_templates.stat_type_1",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_stat_templates.stat_type_2"] = {
                    columnName = "stat_type_2",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.item_stat_templates.stat_type_2",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_stat_templates.stat_type_3"] = {
                    columnName = "stat_type_3",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 4,
                    persistentId = "postgres.item_stat_templates.stat_type_3",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_stat_templates.stat_type_4"] = {
                    columnName = "stat_type_4",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 5,
                    persistentId = "postgres.item_stat_templates.stat_type_4",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_stat_templates.stat_type_5"] = {
                    columnName = "stat_type_5",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 6,
                    persistentId = "postgres.item_stat_templates.stat_type_5",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_stat_templates.stat_type_6"] = {
                    columnName = "stat_type_6",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 7,
                    persistentId = "postgres.item_stat_templates.stat_type_6",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_stat_templates.stat_type_7"] = {
                    columnName = "stat_type_7",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 8,
                    persistentId = "postgres.item_stat_templates.stat_type_7",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_stat_templates.stat_type_8"] = {
                    columnName = "stat_type_8",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 9,
                    persistentId = "postgres.item_stat_templates.stat_type_8",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_stat_templates.stat_value_1"] = {
                    columnName = "stat_value_1",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 10,
                    persistentId = "postgres.item_stat_templates.stat_value_1",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_stat_templates.stat_value_2"] = {
                    columnName = "stat_value_2",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 11,
                    persistentId = "postgres.item_stat_templates.stat_value_2",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_stat_templates.stat_value_3"] = {
                    columnName = "stat_value_3",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 12,
                    persistentId = "postgres.item_stat_templates.stat_value_3",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_stat_templates.stat_value_4"] = {
                    columnName = "stat_value_4",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 13,
                    persistentId = "postgres.item_stat_templates.stat_value_4",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_stat_templates.stat_value_5"] = {
                    columnName = "stat_value_5",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 14,
                    persistentId = "postgres.item_stat_templates.stat_value_5",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_stat_templates.stat_value_6"] = {
                    columnName = "stat_value_6",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 15,
                    persistentId = "postgres.item_stat_templates.stat_value_6",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_stat_templates.stat_value_7"] = {
                    columnName = "stat_value_7",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 16,
                    persistentId = "postgres.item_stat_templates.stat_value_7",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_stat_templates.stat_value_8"] = {
                    columnName = "stat_value_8",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 17,
                    persistentId = "postgres.item_stat_templates.stat_value_8",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.item_stat_templates",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.item_stat_templates.id",
                    },
                },
                name = "item_stat_templates_pkey",
                persistentId = "postgres.item_stat_templates.pk",
                signature = "item_stat_templates_pkey|postgres.item_stat_templates.id:asc",
            },
            schema = "public",
            tableName = "item_stat_templates",
        },
        ["postgres.item_templates"] = {
            constraints = {
            },
            fields = {
                ["postgres.item_templates.armor"] = {
                    columnName = "armor",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 13,
                    persistentId = "postgres.item_templates.armor",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_templates.armor_template_id"] = {
                    columnName = "armor_template_id",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 15,
                    persistentId = "postgres.item_templates.armor_template_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_templates.bind"] = {
                    columnName = "bind",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.item_templates.bind",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_templates.category"] = {
                    columnName = "category",
                    defaultValue = 1,
                    hasDefault = true,
                    nullable = false,
                    order = 5,
                    persistentId = "postgres.item_templates.category",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_templates.description"] = {
                    columnName = "description",
                    defaultValue = "",
                    hasDefault = true,
                    nullable = false,
                    order = 12,
                    persistentId = "postgres.item_templates.description",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
                ["postgres.item_templates.display_id"] = {
                    columnName = "display_id",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.item_templates.display_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_templates.durability"] = {
                    columnName = "durability",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 9,
                    persistentId = "postgres.item_templates.durability",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_templates.icon_id"] = {
                    columnName = "icon_id",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 10,
                    persistentId = "postgres.item_templates.icon_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_templates.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.item_templates.id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_templates.name"] = {
                    columnName = "name",
                    hasDefault = false,
                    nullable = false,
                    order = 11,
                    persistentId = "postgres.item_templates.name",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
                ["postgres.item_templates.rarity"] = {
                    columnName = "rarity",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 4,
                    persistentId = "postgres.item_templates.rarity",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_templates.required_level"] = {
                    columnName = "required_level",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 8,
                    persistentId = "postgres.item_templates.required_level",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_templates.shield_template_id"] = {
                    columnName = "shield_template_id",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 17,
                    persistentId = "postgres.item_templates.shield_template_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_templates.stat_template_id"] = {
                    columnName = "stat_template_id",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 14,
                    persistentId = "postgres.item_templates.stat_template_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_templates.type"] = {
                    columnName = "type",
                    defaultValue = 1,
                    hasDefault = true,
                    nullable = false,
                    order = 6,
                    persistentId = "postgres.item_templates.type",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_templates.virtual_level"] = {
                    columnName = "virtual_level",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 7,
                    persistentId = "postgres.item_templates.virtual_level",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.item_templates.weapon_template_id"] = {
                    columnName = "weapon_template_id",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 16,
                    persistentId = "postgres.item_templates.weapon_template_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.item_templates",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.item_templates.id",
                    },
                },
                name = "item_templates_pkey",
                persistentId = "postgres.item_templates.pk",
                signature = "item_templates_pkey|postgres.item_templates.id:asc",
            },
            schema = "public",
            tableName = "item_templates",
        },
        ["postgres.item_weapon_templates"] = {
            constraints = {
            },
            fields = {
                ["postgres.item_weapon_templates.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.item_weapon_templates.id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_weapon_templates.max_damage"] = {
                    columnName = "max_damage",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 4,
                    persistentId = "postgres.item_weapon_templates.max_damage",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_weapon_templates.min_damage"] = {
                    columnName = "min_damage",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.item_weapon_templates.min_damage",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.item_weapon_templates.speed"] = {
                    columnName = "speed",
                    defaultValue = 1.0,
                    hasDefault = true,
                    nullable = false,
                    order = 5,
                    persistentId = "postgres.item_weapon_templates.speed",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.item_weapon_templates.weapon_style"] = {
                    columnName = "weapon_style",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.item_weapon_templates.weapon_style",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.item_weapon_templates",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.item_weapon_templates.id",
                    },
                },
                name = "item_weapon_templates_pkey",
                persistentId = "postgres.item_weapon_templates.pk",
                signature = "item_weapon_templates_pkey|postgres.item_weapon_templates.id:asc",
            },
            schema = "public",
            tableName = "item_weapon_templates",
        },
        ["postgres.map_locations"] = {
            constraints = {
                ["postgres.map_locations.map_locations_map_fk"] = {
                    kind = "foreignKey",
                    name = "map_locations_map_fk",
                    persistentId = "postgres.map_locations.map_locations_map_fk",
                    signature = "foreignKey|map_locations_map_fk|postgres.map_locations.map_id:asc||nil:nil||postgres.maps|postgres.maps.id:asc|noAction|noAction",
                },
            },
            fields = {
                ["postgres.map_locations.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.map_locations.id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.map_locations.map_id"] = {
                    columnName = "map_id",
                    hasDefault = false,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.map_locations.map_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.map_locations.name"] = {
                    columnName = "name",
                    defaultValue = "",
                    hasDefault = true,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.map_locations.name",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
                ["postgres.map_locations.position_o"] = {
                    columnName = "position_o",
                    defaultValue = 0.0,
                    hasDefault = true,
                    nullable = false,
                    order = 7,
                    persistentId = "postgres.map_locations.position_o",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.map_locations.position_x"] = {
                    columnName = "position_x",
                    defaultValue = 0.0,
                    hasDefault = true,
                    nullable = false,
                    order = 4,
                    persistentId = "postgres.map_locations.position_x",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.map_locations.position_y"] = {
                    columnName = "position_y",
                    defaultValue = 0.0,
                    hasDefault = true,
                    nullable = false,
                    order = 5,
                    persistentId = "postgres.map_locations.position_y",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.map_locations.position_z"] = {
                    columnName = "position_z",
                    defaultValue = 0.0,
                    hasDefault = true,
                    nullable = false,
                    order = 6,
                    persistentId = "postgres.map_locations.position_z",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.map_locations",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.map_locations.id",
                    },
                },
                name = "map_locations_pkey",
                persistentId = "postgres.map_locations.pk",
                signature = "map_locations_pkey|postgres.map_locations.id:asc",
            },
            schema = "public",
            tableName = "map_locations",
        },
        ["postgres.maps"] = {
            constraints = {
            },
            fields = {
                ["postgres.maps.flags"] = {
                    columnName = "flags",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.maps.flags",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.maps.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.maps.id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.maps.internal_name"] = {
                    columnName = "internal_name",
                    defaultValue = "",
                    hasDefault = true,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.maps.internal_name",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
                ["postgres.maps.max_players"] = {
                    columnName = "max_players",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 6,
                    persistentId = "postgres.maps.max_players",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.maps.name"] = {
                    columnName = "name",
                    defaultValue = "",
                    hasDefault = true,
                    nullable = false,
                    order = 4,
                    persistentId = "postgres.maps.name",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
                ["postgres.maps.type"] = {
                    columnName = "type",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 5,
                    persistentId = "postgres.maps.type",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.maps",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.maps.id",
                    },
                },
                name = "maps_pkey",
                persistentId = "postgres.maps.pk",
                signature = "maps_pkey|postgres.maps.id:asc",
            },
            schema = "public",
            tableName = "maps",
        },
        ["postgres.permission_group_data"] = {
            constraints = {
                ["postgres.permission_group_data.permission_group_data_group_fk"] = {
                    kind = "foreignKey",
                    name = "permission_group_data_group_fk",
                    persistentId = "postgres.permission_group_data.permission_group_data_group_fk",
                    signature = "foreignKey|permission_group_data_group_fk|postgres.permission_group_data.group_id:asc||nil:nil||postgres.permission_groups|postgres.permission_groups.id:asc|noAction|cascade",
                },
                ["postgres.permission_group_data.permission_group_data_key"] = {
                    kind = "unique",
                    name = "permission_group_data_key",
                    persistentId = "postgres.permission_group_data.permission_group_data_key",
                    signature = "unique|permission_group_data_key|postgres.permission_group_data.group_id:asc,postgres.permission_group_data.permission_id:asc||nil:nil|||||",
                },
                ["postgres.permission_group_data.permission_group_data_permission_fk"] = {
                    kind = "foreignKey",
                    name = "permission_group_data_permission_fk",
                    persistentId = "postgres.permission_group_data.permission_group_data_permission_fk",
                    signature = "foreignKey|permission_group_data_permission_fk|postgres.permission_group_data.permission_id:asc||nil:nil||postgres.permissions|postgres.permissions.id:asc|noAction|cascade",
                },
            },
            fields = {
                ["postgres.permission_group_data.group_id"] = {
                    columnName = "group_id",
                    hasDefault = false,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.permission_group_data.group_id",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.permission_group_data.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.permission_group_data.id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.permission_group_data.permission_id"] = {
                    columnName = "permission_id",
                    hasDefault = false,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.permission_group_data.permission_id",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.permission_group_data",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.permission_group_data.id",
                    },
                },
                name = "permission_group_data_pkey",
                persistentId = "postgres.permission_group_data.pk",
                signature = "permission_group_data_pkey|postgres.permission_group_data.id:asc",
            },
            schema = "public",
            tableName = "permission_group_data",
        },
        ["postgres.permission_groups"] = {
            constraints = {
                ["postgres.permission_groups.permission_groups_unique_name"] = {
                    kind = "unique",
                    name = "permission_groups_unique_name",
                    persistentId = "postgres.permission_groups.permission_groups_unique_name",
                    signature = "unique|permission_groups_unique_name|postgres.permission_groups.name:asc||nil:nil|||||",
                },
            },
            fields = {
                ["postgres.permission_groups.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.permission_groups.id",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.permission_groups.name"] = {
                    columnName = "name",
                    hasDefault = false,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.permission_groups.name",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.permission_groups",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.permission_groups.id",
                    },
                },
                name = "permission_groups_pkey",
                persistentId = "postgres.permission_groups.pk",
                signature = "permission_groups_pkey|postgres.permission_groups.id:asc",
            },
            schema = "public",
            tableName = "permission_groups",
        },
        ["postgres.permissions"] = {
            constraints = {
                ["postgres.permissions.permissions_unique_name"] = {
                    kind = "unique",
                    name = "permissions_unique_name",
                    persistentId = "postgres.permissions.permissions_unique_name",
                    signature = "unique|permissions_unique_name|postgres.permissions.name:asc||nil:nil|||||",
                },
            },
            fields = {
                ["postgres.permissions.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.permissions.id",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.permissions.name"] = {
                    columnName = "name",
                    hasDefault = false,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.permissions.name",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.permissions",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.permissions.id",
                    },
                },
                name = "permissions_pkey",
                persistentId = "postgres.permissions.pk",
                signature = "permissions_pkey|postgres.permissions.id:asc",
            },
            schema = "public",
            tableName = "permissions",
        },
        ["postgres.proximity_triggers"] = {
            constraints = {
            },
            fields = {
                ["postgres.proximity_triggers.extents_x"] = {
                    columnName = "extents_x",
                    defaultValue = 1.0,
                    hasDefault = true,
                    nullable = false,
                    order = 8,
                    persistentId = "postgres.proximity_triggers.extents_x",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.proximity_triggers.extents_y"] = {
                    columnName = "extents_y",
                    defaultValue = 1.0,
                    hasDefault = true,
                    nullable = false,
                    order = 9,
                    persistentId = "postgres.proximity_triggers.extents_y",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.proximity_triggers.extents_z"] = {
                    columnName = "extents_z",
                    defaultValue = 1.0,
                    hasDefault = true,
                    nullable = false,
                    order = 10,
                    persistentId = "postgres.proximity_triggers.extents_z",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.proximity_triggers.flags"] = {
                    columnName = "flags",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.proximity_triggers.flags",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.proximity_triggers.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.proximity_triggers.id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.proximity_triggers.map_id"] = {
                    columnName = "map_id",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 4,
                    persistentId = "postgres.proximity_triggers.map_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.proximity_triggers.name"] = {
                    columnName = "name",
                    defaultValue = "",
                    hasDefault = true,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.proximity_triggers.name",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
                ["postgres.proximity_triggers.position_x"] = {
                    columnName = "position_x",
                    defaultValue = 0.0,
                    hasDefault = true,
                    nullable = false,
                    order = 5,
                    persistentId = "postgres.proximity_triggers.position_x",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.proximity_triggers.position_y"] = {
                    columnName = "position_y",
                    defaultValue = 0.0,
                    hasDefault = true,
                    nullable = false,
                    order = 6,
                    persistentId = "postgres.proximity_triggers.position_y",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.proximity_triggers.position_z"] = {
                    columnName = "position_z",
                    defaultValue = 0.0,
                    hasDefault = true,
                    nullable = false,
                    order = 7,
                    persistentId = "postgres.proximity_triggers.position_z",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
            },
            indexes = {
                ["postgres.proximity_triggers.map_id_idx"] = {
                    fields = {
                        [1] = {
                            columnName = "map_id",
                            direction = "asc",
                            persistentId = "postgres.proximity_triggers.map_id",
                        },
                    },
                    name = "proximity_triggers_map_id_idx",
                    persistentId = "postgres.proximity_triggers.map_id_idx",
                    signature = "proximity_triggers_map_id_idx|false|postgres.proximity_triggers.map_id:asc",
                    unique = false,
                },
            },
            persistentId = "postgres.proximity_triggers",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.proximity_triggers.id",
                    },
                },
                name = "proximity_triggers_pkey",
                persistentId = "postgres.proximity_triggers.pk",
                signature = "proximity_triggers_pkey|postgres.proximity_triggers.id:asc",
            },
            schema = "public",
            tableName = "proximity_triggers",
        },
        ["postgres.spell_effects"] = {
            constraints = {
            },
            fields = {
                ["postgres.spell_effects.effect_misc_value_1"] = {
                    columnName = "effect_misc_value_1",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 8,
                    persistentId = "postgres.spell_effects.effect_misc_value_1",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spell_effects.effect_misc_value_2"] = {
                    columnName = "effect_misc_value_2",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 9,
                    persistentId = "postgres.spell_effects.effect_misc_value_2",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spell_effects.effect_misc_value_3"] = {
                    columnName = "effect_misc_value_3",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 10,
                    persistentId = "postgres.spell_effects.effect_misc_value_3",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spell_effects.effect_priority"] = {
                    columnName = "effect_priority",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.spell_effects.effect_priority",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.spell_effects.effect_type"] = {
                    columnName = "effect_type",
                    hasDefault = false,
                    nullable = false,
                    order = 4,
                    persistentId = "postgres.spell_effects.effect_type",
                    postgresType = {
                        name = "smallint",
                        sql = "smallint",
                    },
                },
                ["postgres.spell_effects.effect_value_1"] = {
                    columnName = "effect_value_1",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 5,
                    persistentId = "postgres.spell_effects.effect_value_1",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spell_effects.effect_value_2"] = {
                    columnName = "effect_value_2",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 6,
                    persistentId = "postgres.spell_effects.effect_value_2",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spell_effects.effect_value_3"] = {
                    columnName = "effect_value_3",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 7,
                    persistentId = "postgres.spell_effects.effect_value_3",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spell_effects.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.spell_effects.id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spell_effects.spell_id"] = {
                    columnName = "spell_id",
                    hasDefault = false,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.spell_effects.spell_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.spell_effects",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.spell_effects.id",
                    },
                },
                name = "spell_effects_pkey",
                persistentId = "postgres.spell_effects.pk",
                signature = "spell_effects_pkey|postgres.spell_effects.id:asc",
            },
            schema = "public",
            tableName = "spell_effects",
        },
        ["postgres.spell_proc_data"] = {
            constraints = {
            },
            fields = {
                ["postgres.spell_proc_data.chance_to_proc"] = {
                    columnName = "chance_to_proc",
                    defaultValue = 0.0,
                    hasDefault = true,
                    nullable = false,
                    order = 7,
                    persistentId = "postgres.spell_proc_data.chance_to_proc",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.spell_proc_data.charges"] = {
                    columnName = "charges",
                    defaultValue = -1,
                    hasDefault = true,
                    nullable = false,
                    order = 9,
                    persistentId = "postgres.spell_proc_data.charges",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spell_proc_data.flags"] = {
                    columnName = "flags",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 5,
                    persistentId = "postgres.spell_proc_data.flags",
                    postgresType = {
                        name = "bigint",
                        sql = "bigint",
                    },
                },
                ["postgres.spell_proc_data.hit_mask"] = {
                    columnName = "hit_mask",
                    defaultValue = -1,
                    hasDefault = true,
                    nullable = false,
                    order = 4,
                    persistentId = "postgres.spell_proc_data.hit_mask",
                    postgresType = {
                        name = "bigint",
                        sql = "bigint",
                    },
                },
                ["postgres.spell_proc_data.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.spell_proc_data.id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spell_proc_data.internal_cooldown_ms"] = {
                    columnName = "internal_cooldown_ms",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 8,
                    persistentId = "postgres.spell_proc_data.internal_cooldown_ms",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spell_proc_data.phase_mask"] = {
                    columnName = "phase_mask",
                    defaultValue = -1,
                    hasDefault = true,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.spell_proc_data.phase_mask",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spell_proc_data.procs_per_min"] = {
                    columnName = "procs_per_min",
                    defaultValue = 1.0,
                    hasDefault = true,
                    nullable = false,
                    order = 6,
                    persistentId = "postgres.spell_proc_data.procs_per_min",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.spell_proc_data.type_mask"] = {
                    columnName = "type_mask",
                    defaultValue = -1,
                    hasDefault = true,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.spell_proc_data.type_mask",
                    postgresType = {
                        name = "bigint",
                        sql = "bigint",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.spell_proc_data",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.spell_proc_data.id",
                    },
                },
                name = "spell_proc_data_pkey",
                persistentId = "postgres.spell_proc_data.pk",
                signature = "spell_proc_data_pkey|postgres.spell_proc_data.id:asc",
            },
            schema = "public",
            tableName = "spell_proc_data",
        },
        ["postgres.spell_proc_link"] = {
            constraints = {
            },
            fields = {
                ["postgres.spell_proc_link.effect_mask"] = {
                    columnName = "effect_mask",
                    defaultValue = -1,
                    hasDefault = true,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.spell_proc_link.effect_mask",
                    postgresType = {
                        name = "bigint",
                        sql = "bigint",
                    },
                },
                ["postgres.spell_proc_link.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.spell_proc_link.id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spell_proc_link.proc_data_id"] = {
                    columnName = "proc_data_id",
                    hasDefault = false,
                    nullable = false,
                    order = 4,
                    persistentId = "postgres.spell_proc_link.proc_data_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spell_proc_link.spell_id"] = {
                    columnName = "spell_id",
                    hasDefault = false,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.spell_proc_link.spell_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.spell_proc_link",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.spell_proc_link.id",
                    },
                },
                name = "spell_proc_link_pkey",
                persistentId = "postgres.spell_proc_link.pk",
                signature = "spell_proc_link_pkey|postgres.spell_proc_link.id:asc",
            },
            schema = "public",
            tableName = "spell_proc_link",
        },
        ["postgres.spells"] = {
            constraints = {
            },
            fields = {
                ["postgres.spells.aura_description"] = {
                    columnName = "aura_description",
                    defaultValue = "",
                    hasDefault = true,
                    nullable = false,
                    order = 4,
                    persistentId = "postgres.spells.aura_description",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
                ["postgres.spells.cast_time"] = {
                    columnName = "cast_time",
                    defaultValue = 0.0,
                    hasDefault = true,
                    nullable = false,
                    order = 6,
                    persistentId = "postgres.spells.cast_time",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.spells.cooldown"] = {
                    columnName = "cooldown",
                    defaultValue = 0.0,
                    hasDefault = true,
                    nullable = false,
                    order = 7,
                    persistentId = "postgres.spells.cooldown",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.spells.description"] = {
                    columnName = "description",
                    defaultValue = "",
                    hasDefault = true,
                    nullable = false,
                    order = 3,
                    persistentId = "postgres.spells.description",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
                ["postgres.spells.duration"] = {
                    columnName = "duration",
                    defaultValue = 0.0,
                    hasDefault = true,
                    nullable = false,
                    order = 8,
                    persistentId = "postgres.spells.duration",
                    postgresType = {
                        name = "real",
                        sql = "real",
                    },
                },
                ["postgres.spells.icon_id"] = {
                    columnName = "icon_id",
                    defaultValue = 0,
                    hasDefault = true,
                    nullable = false,
                    order = 5,
                    persistentId = "postgres.spells.icon_id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spells.id"] = {
                    columnName = "id",
                    hasDefault = false,
                    identity = "byDefault",
                    nullable = false,
                    order = 1,
                    persistentId = "postgres.spells.id",
                    postgresType = {
                        name = "integer",
                        sql = "integer",
                    },
                },
                ["postgres.spells.name"] = {
                    columnName = "name",
                    defaultValue = "",
                    hasDefault = true,
                    nullable = false,
                    order = 2,
                    persistentId = "postgres.spells.name",
                    postgresType = {
                        name = "text",
                        sql = "text",
                    },
                },
            },
            indexes = {
            },
            persistentId = "postgres.spells",
            primaryKey = {
                fields = {
                    [1] = {
                        columnName = "id",
                        direction = "asc",
                        persistentId = "postgres.spells.id",
                    },
                },
                name = "spells_pkey",
                persistentId = "postgres.spells.pk",
                signature = "spells_pkey|postgres.spells.id:asc",
            },
            schema = "public",
            tableName = "spells",
        },
    },
}
